language: node_js
node_js:
  - "10"
before_install:
  - git config --global user.name "liujian10"
  - git config --global user.email "mapleliu1@gmail.com"
script:
  - npm run build:demo
  - cd build
  - git init
  - git add -A
  - git commit -m "Deploy GH"
  - git push -u https://$GH_TOKEN@github.com/liujian10/redux-hook.git HEAD:gh-pages --force
cache:
  directories:
    - node_modules
